version: "3.9"

services:
  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ../api/app:/var/www/html/app

  php:
    container_name: ${PHP_CONTAINER_NAME}
    build: images/php
    volumes:
      - ../api:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mariadb:10.5.8
    restart: 'always'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
